apiVersion: builtin
kind: PatchTransformer
metadata:
  name: gpu-hostlabel
target:
  kind: Metal3MachineTemplate
patch: |-
  - op: replace
    path: /spec/template/spec/hostSelector/matchLabels/gpu
    value: "true"
