apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - vspheremachinetemplate-ingress.yaml
patches:
  - target:
      kind: MachineDeployment
      name: mdw-0
    path: patches/machinedeployment-ingress-bootstrap.yaml
  - target:
      kind: MachineDeployment
      name: mdw-0
    path: patches/machinedeployment-ingress.yaml
