apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: ingress
  annotations:
    internal.config.kubernetes.io/needsHashSuffix: enabled
spec:
  template:
    spec: {}
