apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - build/
transformers:
  - ../_replacements/metal3/
components:
  - ../../../topologies/_annotations/zone-topology-local-config
