apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../common
  - kube-vip

resources:
  - vspheremachinetemplate-cp.yaml

transformers:
  - transformers/vsphere-cp-network-from-topology.yaml
  - _kcs-cp-additions/
  - ../../../bootstrap/kubeadm/_replacements/hack-netplan/
  - _replacements/kube-vip/
  - _replacements/kcs-to-kcp/

patches:
  - target:
      kind: KubeadmControlPlane
    path: patches/kubeadmcontrolplane-infra-kind.yaml
