---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer
spec:
  secretName: etcd-peer-tls
  isCA: false
  usages:
    - "server auth"
    - "client auth"
    - "signing"
    - "key encipherment"
  dnsNames:
    - etcd-0
    - etcd-0.etcd-headless
    - etcd-0.etcd-headless.${clusterName}.svc
    - etcd-0.etcd-headless.${clusterName}.svc.${breederCluster}
    - etcd-1
    - etcd-1.etcd-headless
    - etcd-1.etcd-headless.${clusterName}.svc
    - etcd-1.etcd-headless.${clusterName}.svc.${breederCluster}
    - etcd-2
    - etcd-2.etcd-headless
    - etcd-2.etcd-headless.${clusterName}.svc
    - etcd-2.etcd-headless.${clusterName}.svc.${breederCluster}
    - localhost
    - "127.0.0.1"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  issuerRef:
    name: etcd-peer-issuer
