apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - kamajicontrolplane.yaml
  - ingress.yaml
  - datastore.yaml
  - etcdcluster.yaml
  - certificate-ca.yaml
  - certificate-client.yaml
  - certificate-peer-ca.yaml
  - certificate-peer.yaml
  - certificate-server.yaml
  - issuer-ca.yaml
  - issuer-peer.yaml
  - issuer-selfsigning.yaml
patches:
  - target:
      kind: Cluster
    path: patches/cluster.yaml
  - target:
      kind: Namespace
    path: patches/namespace.yaml
