apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  labels:
    cluster.x-k8s.io/cluster-name: test
  annotations:
    kustomize.toolkit.fluxcd.io/kustomization-path: "/base"
spec:
  components:
    - ../_refs
    - ../infra/kubevirt
    - ../topologies/demo-kubevirt
    - ../zones/north/kubevirt
    - ../zones/south/kubevirt
    - ../zones/east/kubevirt
    - ../bootstrap/kubeadm/kubevirt
    - ../control-plane/kubeadm/kubevirt
  force: false
  prune: true
  interval: 10m0s
  path: /base
  sourceRef:
    kind: GitRepository
    name: capi-mgmt
    namespace: flux-system
  postBuild:
    substitute:
      breederCluster: management.example.com
      bundleRelease: bundle-v1.30-rolling-release
      clusterFQDN: demo-kv-kubeadm.cluster.example.com
      clusterName: demo-kv-kubeadm
      clusterVRF: DEMO-VRF
      controlPlaneEndpoint: 127.0.0.1
      cpCount: "3"
      cpCores: "2"
      cpDisk: "25"
      cpMem: "4096"
      flatcarVersion: "4230.1.1"
      flatcarContainerDisk: registry.example.com/org/kubevirt/containerdisks/flatcar:4230.1.1
      kubeVersion: v1.30.1
      kubevirtControlPlaneServiceType: LoadBalancer
      imageRepository: "${imageRepository}"
      artifactBaseUrl: "${artifactBaseUrl}"
      podCIDR: 10.129.0.0/16
      profileName: dev-minimal
      svcCIDR: 10.97.0.0/16
      sshKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExampleKeyReplaceWithYourOwn ops@example.com
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
      - kind: Secret
        name: flux-cluster-secrets
