apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - sshkeys.yaml
replacements:
- source:
    kind: ConfigMap
    name: ssh-keys
    fieldPath: data.sshKeys
  targets:
  - select:
      kind: KubeadmControlPlane
    fieldPaths:
      - spec.kubeadmConfigSpec.users.0.sshAuthorizedKeys
  - select:
      kind: KubeadmConfigTemplate
    fieldPaths:
      - spec.template.spec.users.0.sshAuthorizedKeys