apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - kubeadm-bootstrap-users.yaml
replacements:
  - source:
      kind: KubeadmBootstrapUsers
      name: ssh-users
      fieldPath: spec.users
    targets:
      - select:
          kind: KubeadmConfigSpec
          name: kcs
        fieldPaths:
          - spec.users
