apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-keys
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  sshKeys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExampleKeyReplaceWithYourOwn ops@example.com