apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.${clusterFQDN},kubernetes.default.svc.${clusterFQDN}
spec:
  initContainers:
  - name: delay
    image: >-
      ${imageRepository}/busybox:1.34.0
    command:
      - sh
    args:
      - '-c'
      - 'until nc localhost 6443; do echo "Waiting for kube-apiserver"; sleep 1; done'
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    imagePullPolicy: Always
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
  containers:
  - args:
    - manager
    env:
      - name: vip_interface
        value: lo
      - name: vip_loglevel
        value: "5"
      - name: cp_enable
        value: "true"
      - name: cp_namespace
        value: kube-system
      - name: vip_arp
        value: "false"
      - name: port
        value: "6443"
      - name: vip_cidr
        value: "32"
      - name: bgp_enable
        value: "true"
      - name: bgp_routerid
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: bgp_as
        value: ${bgpAS}
      - name: bgp_peers
        value: ${bgpPeers}
      - name: address
        value: ${controlPlaneEndpoint}
      - name: bgp_routerinterface
        value: ${vipNetworkInterface:=ens192}
      - name: vip_singlenode
        value: "true"
    image: ${imageRepository}/kube-vip/kube-vip:v0.8.6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health?exclude=NOSPACE&serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/hosts
      name: etchosts
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
      type: File
    name: kubeconfig
  - hostPath:
      path: /etc/kube-vip.hosts
      type: File
    name: etchosts
status: {}
