apiVersion: topology.clusters.local/v1alpha1
kind: ZoneTopology
metadata:
  name: south-zone-topology
  annotations: {}
spec:
  region: sitea
  zone: south
  vcNetwork: ""
  groups:
    enp33-gpu:
      replicas: 1
    enp33-nongpu:
      replicas: 1
    ens81-gpu:
      replicas: 1
    ens81-nongpu:
      replicas: 1
    eno5eno6-gpu:
      replicas: 1
    eno5eno6-nongpu:
      replicas: 1
  ippool:
    dnsServers:
      - 192.0.2.10
      - 192.0.2.11
      - 192.0.2.12
    addresses:
      - 203.0.113.0-203.0.113.0
    gateway: 203.0.113.1
    prefix: "24"
    pools:
      - start: 203.0.113.0
        end: 203.0.113.0
        prefix: 24
        gateway: 203.0.113.1
