apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - kubevirtcluster.yaml

patches:
  - target:
      kind: Cluster
    path: patches/cluster.yaml
  - target:
      kind: Namespace
    path: patches/namespace.yaml
