apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../_suffixes/nic-group
patches:
  - target:
      kind: PrefixSuffixTransformer
      name: nic-group
    patch: |-
      - op: replace
        path: /suffix
        value: "-ens81"
