apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: topology-replacements-metal3
replacements:
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.groups.enp33-gpu.replicas
    targets:
      - select:
          kind: MachineDeployment
          name: mdw-0-enp33-gpu
        fieldPaths:
          - spec.replicas
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.groups.enp33-nongpu.replicas
    targets:
      - select:
          kind: MachineDeployment
          name: mdw-0-enp33-nongpu
        fieldPaths:
          - spec.replicas
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.groups.ens81-gpu.replicas
    targets:
      - select:
          kind: MachineDeployment
          name: mdw-0-ens81-gpu
        fieldPaths:
          - spec.replicas
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.groups.ens81-nongpu.replicas
    targets:
      - select:
          kind: MachineDeployment
          name: mdw-0-ens81-nongpu
        fieldPaths:
          - spec.replicas
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.groups.eno5eno6-gpu.replicas
    targets:
      - select:
          kind: MachineDeployment
          name: mdw-0-eno5eno6-gpu
        fieldPaths:
          - spec.replicas
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.groups.eno5eno6-nongpu.replicas
    targets:
      - select:
          kind: MachineDeployment
          name: mdw-0-eno5eno6-nongpu
        fieldPaths:
          - spec.replicas
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.ippool
    targets:
      - select:
          kind: IPPool
          name: \${clusterName}
        fieldPaths:
          - spec
