apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: topology-replacements-metal3
replacements:
  - source:
      kind: ZoneTopology
      name: zone-topology
      fieldPath: spec.ippool
    targets:
      - select:
          kind: IPPool
          name: \${clusterName}
        fieldPaths:
          - spec
