apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metal3-nic-enp33.yaml
  - metal3-nic-ens81.yaml
  - metal3-nic-eno5eno6.yaml
  - metal3-nic-enp35.yaml
  - metal3-nic-enp83.yaml
  - metal3-nic-ens1.yaml
  - metal3-nic-ens2.yaml
  - metal3-nic-ens22.yaml
