apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: EtcdCluster
    path: patches/etcdcluster.yaml
  - target:
      kind: KamajiControlPlane
    path: patches/kamajicontrolplane.yaml
