apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: cp-kubevirt
  labels:
    cluster.x-k8s.io/control-plane: "true"
  annotations:
    internal.config.kubernetes.io/needsHashSuffix: enabled
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: ${clusterName}
        spec:
          runStrategy: Always
          template:
            metadata:
              annotations:
                kubevirt.io/allow-pod-bridge-network-live-migration: "true"
            spec:
              architecture: amd64
              domain:
                cpu:
                  cores: ${cpCores}
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: containervolume
                  networkInterfaceMultiqueue: true
                machine:
                  type: q35
                resources:
                  requests:
                    memory: ${cpMem}Mi
              evictionStrategy: External
              volumes:
                - containerDisk:
                    image: ${flatcarContainerDisk}
                  name: containervolume
