apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: zone-topology-local-config
annotations:
  config.kubernetes.io/local-config: "true"
fieldSpecs:
  - path: metadata/annotations
    kind: ZoneTopology
    create: true
