apiVersion: topology.clusters.local/v1alpha1
kind: ZoneTopology
metadata:
  name: east-zone-topology
  annotations: {}
spec:
  region: sitea
  zone: east
  ippool:
    addresses:
      - 192.0.2.200-192.0.2.205
    gateway: 192.0.2.1
    prefix: 24
  vcNetwork: APPMGMT-EAST-V282
  groups:
    worker:
      replicas: 1
      vmtSpec:
        diskGiB: 64
        memoryMiB: 32768
        numCPUs: 8
        resourcePool: /SiteA-DC/host/SiteA-East-ESXi01/SiteA-East-Cluster01/Resources/east-${clusterName}
        template: capi-templates/east-flatcar-stable-3815.2.0-plain
        network:
          devices:
            - dhcp4: false
              addressesFromPools:
                - apiGroup: ipam.cluster.x-k8s.io
                  kind: InClusterIPPool
                  name: ippool
              networkName: APPMGMT-EAST-V282
              nameservers:
                - 192.0.2.10
                - 192.0.2.11
                - 192.0.2.12
    ingress:
      replicas: 1
      vmtSpec:
        diskGiB: 64
        memoryMiB: 32768
        numCPUs: 8
        resourcePool: /SiteA-DC/host/SiteA-East-ESXi01/SiteA-East-Cluster01/Resources/east-${clusterName}
        template: capi-templates/east-flatcar-stable-3815.2.0-plain
        network:
          devices:
            - dhcp4: false
              addressesFromPools:
                - apiGroup: ipam.cluster.x-k8s.io
                  kind: InClusterIPPool
                  name: ippool
              networkName: APPMGMT-EAST-V282
              nameservers:
                - 192.0.2.10
                - 192.0.2.11
                - 192.0.2.12
